name: Deploy terraform folder
description: Deploy terraform folder using AWS validations
author: André Buchmann

inputs:
  terraform_path:
    description: Path to the Terraform folder.
    required: true
  role_arn:
    description: AWS role that will be assumed to deploy.
    required: true

runs:
  using: "composite"
  steps:
    - name: Get repo
      run: |
        repo_name=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        echo "REPO_NAME=$repo_name" >> $GITHUB_ENV
      shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_arn }}
        aws-region: sa-east-1
        role-session-name: terraform-deploy-${{ env.REPO_NAME }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Initialize Terraform
      run: terraform init
      working-directory: ${{ inputs.terraform_path }}
      shell: bash

    - name: Validate Terraform
      run: terraform validate
      working-directory: ${{ inputs.terraform_path }}
      shell: bash

    - name: Plan Terraform
      run: terraform plan -out=tfplan.binary
      working-directory: ${{ inputs.terraform_path }}
      shell: bash    
      
    - name: Save tfplan to Terraform
      run: |
        terraform show -json tfplan.binary 2>/dev/null | jq . > tfplan.json
      working-directory: ${{ inputs.terraform_path }}
      shell: bash

    - name: Validate IAM Role Policies
      uses: androzo/aws-validation@main
      with:
        tfplan_path: ${{ inputs.terraform_path }}/tfplan.json

    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan.binary
      working-directory: ${{ inputs.terraform_path }}
      shell: bash